### ISSUE TITLE
Needed to install update chromeos's knowlege of the docker packages so I did this first:

### ISSUE THREAD

**Issue by lloydtabb** [micahcatlin/build-looker#1]
https://hackernoon.com/pixelbook-revisited-running-docker-containers-aa7c742a7dec

**Comment by lloydtabb** [comment]
actually, I'm still getting lloydtabb@penguin:~/dev/build-looker/docker-chromeos$ sudo apt-get install docker-ce
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-ce
```

```

**Comment by micahcatlin** [comment]
I just added the apt-get update to this script.  Try now?

https://github.com/micahcatlin/build-looker/blob/master/docker-chromeos/docker-chromeos.sh

**Comment by micahcatlin** [comment]
But you're right - I had forgotten I needed to complete those steps as well. Thanks
